### ISSUE TITLE
Add default tablename for CSS3.0 and KBCORE schemas

### ISSUE THREAD

**Issue by aileenfisher** [LANL-Seismoacoustics/pisces#82]
What do you think about having default tablenames for the standard CSS3.0 tables so that we don't have to declare?  

Jeremy has the following "tables" block in his mtuqview par file that he would like to get rid of, and I think all Pisces is getting from this is the _tablename_ (is that right?):

```
database:
  url: ... 
  schema: css3
  tables:
    wfdisc: wfdisc
    site: site 
    origin: origin 
    event:event 
    affiliation: affiliation 
    sitechan: sitechan
    sensor: sensor
    instrument: instrument
 
```
